import { request } from './client'
export const api = {
  sendOtp: body => request('/api/v1/auth/send-otp', { method: 'POST', body: JSON.stringify(body) }), verifyOtp: body => request('/api/v1/auth/verify-otp', { method: 'POST', body: JSON.stringify(body) }), me: () => request('/api/v1/auth/me'), logout: () => request('/api/v1/auth/logout', { method: 'POST' }),
  profile: () => request('/api/v1/profile'), updateProfile: body => request('/api/v1/profile', { method: 'PATCH', body: JSON.stringify(body) }),
  createDraft: () => request('/api/v1/report/drafts', { method: 'POST' }), current: id => request(`/api/v1/report/drafts/${id}/current`), answer: (id, body) => request(`/api/v1/report/drafts/${id}/answers`, { method: 'POST', body: JSON.stringify(body) }), back: id => request(`/api/v1/report/drafts/${id}/back`, { method: 'POST' }), save: id => request(`/api/v1/report/drafts/${id}/save`, { method: 'POST' }), review: id => request(`/api/v1/report/drafts/${id}/review`), claim: draftId => request('/api/v1/auth/claim-draft', { method: 'POST', body: JSON.stringify({ draftId }) }), submit: id => request(`/api/v1/report/drafts/${id}/submit`, { method: 'POST' }),
  cases: () => request('/api/v1/cases'), case: id => request(`/api/v1/cases/${id}`), timeline: id => request(`/api/v1/cases/${id}/timeline`), messages: id => request(`/api/v1/cases/${id}/messages`), grievance: (id, body) => request(`/api/v1/cases/${id}/grievance`, { method: 'POST', body: JSON.stringify(body) }),
  notifications: () => request('/api/v1/notifications'), readNotification: id => request(`/api/v1/notifications/${id}/read`, { method: 'PATCH' }), readAll: () => request('/api/v1/notifications/read-all', { method: 'PATCH' }),
  checkSuspect: body => request('/api/v1/suspects/check', { method: 'POST', body: JSON.stringify(body) }), reportSuspect: body => request('/api/v1/suspects/reports', { method: 'POST', body: JSON.stringify(body) }),
  createSuspectDraft: body => request('/api/v1/suspects/drafts', { method: 'POST', body: JSON.stringify(body) }), suspectCurrent: id => request(`/api/v1/suspects/drafts/${id}/current`), suspectAnswer: (id, body) => request(`/api/v1/suspects/drafts/${id}/answers`, { method: 'POST', body: JSON.stringify(body) }), suspectBack: id => request(`/api/v1/suspects/drafts/${id}/back`, { method: 'POST' }), suspectSave: id => request(`/api/v1/suspects/drafts/${id}/save`, { method: 'POST' }), claimSuspectDraft: draftId => request('/api/v1/auth/claim-suspect-draft', { method: 'POST', body: JSON.stringify({ draftId }) }), suspectReview: id => request(`/api/v1/suspects/drafts/${id}/review`), suspectSubmit: id => request(`/api/v1/suspects/drafts/${id}/submit`, { method: 'POST' }),
  addReportEvidence: (id, body) => request(`/api/v1/report/drafts/${id}/evidence`, { method: 'POST', body: JSON.stringify(body) }), addSuspectEvidence: (id, body) => request(`/api/v1/suspects/drafts/${id}/evidence`, { method: 'POST', body: JSON.stringify(body) }), reportEvidence: id => request(`/api/v1/report/drafts/${id}/evidence`), suspectEvidence: id => request(`/api/v1/suspects/drafts/${id}/evidence`), caseEvidence: id => request(`/api/v1/cases/${id}/evidence`), addCaseEvidence: (id, body) => request(`/api/v1/cases/${id}/evidence`, { method: 'POST', body: JSON.stringify(body) }), uploadUrl: body => request('/api/v1/evidence/upload-url', { method: 'POST', body: JSON.stringify(body) }),
  caseDetails: id => request(`/api/v1/cases/${id}/details`), caseReportPdf: id => request(`/api/v1/cases/${id}/report.pdf`), adminCase: id => request(`/api/v1/admin/cases/${id}`), adminUpdateCaseStatus: (id, body) => request(`/api/v1/admin/cases/${id}/status`, { method: 'PATCH', body: JSON.stringify(body) }), adminRequestEvidence: (id, body) => request(`/api/v1/admin/cases/${id}/evidence-requests`, { method: 'POST', body: JSON.stringify(body) }), adminAddTimeline: (id, body) => request(`/api/v1/admin/cases/${id}/timeline`, { method: 'POST', body: JSON.stringify(body) }), adminAddMessage: (id, body) => request(`/api/v1/admin/cases/${id}/messages`, { method: 'POST', body: JSON.stringify(body) }),
}
