import React, { useState } from 'react'
import { Link, useLocation, useNavigate } from 'react-router-dom'
import { api } from '../../services/api'
import { useAsync } from '../../hooks/useAsync'
import { useAuth } from '../../context/AuthContext'
import { ErrorBox, Loading } from '../common'
function Notifications({ onClose }) { const state = useAsync(api.notifications, []); const [readError, setReadError] = useState(); const [reading, setReading] = useState(false); const [allRead, setAllRead] = useState(false); const markAllRead = async () => { setReading(true); setReadError(); try { await api.readAll(); setAllRead(true) } catch (error) { setReadError(error) } finally { setReading(false) } }; return <aside className="drawer"><div className="drawer-header"><h2>Notifications</h2><button type="button" className="drawer-close" onClick={onClose} aria-label="Close notifications">×</button></div>{state.loading ? <Loading/> : state.error ? <ErrorBox error={state.error}/> : state.data.notifications.length ? <><div className="drawer-actions"><span>{state.data.notifications.length} notification{state.data.notifications.length === 1 ? '' : 's'}</span><button type="button" className="read-all-button" onClick={markAllRead} disabled={reading || allRead}>{reading ? 'Marking…' : allRead ? 'All read' : 'Mark all as read'}</button></div>{state.data.notifications.map(n => <div className={`drawer-item ${allRead || n.readAt ? 'is-read' : ''}`} key={n.id}><strong>{n.title}</strong><p>{n.message}</p></div>)}</> : <p>No notifications yet.</p>}<ErrorBox error={readError}/></aside> }
export function FullLayout({ children }) { const [open, setOpen] = useState(false); const location = useLocation(); return <div className="shell"><header><Link className="brand" to="/"><span>NATIONAL CYBERCRIME</span><strong>REPORTING PORTAL - NCRP</strong></Link><nav><Link className={location.pathname === '/' ? 'active' : ''} to="/">Home</Link><Link to="/report">Report</Link><Link to="/cases">My Cases</Link><button className="nav-button" onClick={() => setOpen(!open)}>Notifications</button><Link to="/profile">Profile</Link></nav></header>{open && <Notifications onClose={() => setOpen(false)}/>}<main>{children}</main><footer><div><strong>Citizen services</strong>Report cybercrime<br/>Check suspicious identifier<br/>Track complaint</div><div><strong>Help</strong>FAQs<br/>Cyber safety<br/>Contact / Support</div><div><strong>Information</strong>About NCRP<br/>Privacy<br/>Terms</div><div><strong>Government resources</strong>Official cybercrime resources</div><div className="brandline"><span>NCRP</span><span>Government of India</span></div><div className="footer-credit">A Project made for "Build What Moves India" Hackathon by Varun Mayya</div></footer></div> }
export function ReportLayout({ children }) { const navigate = useNavigate(); const [saving,setSaving]=useState(false); const save=async()=>{setSaving(true);window.dispatchEvent(new CustomEvent('ncrp-save-report'));setTimeout(()=>setSaving(false),700)}; return <div className="shell report-shell"><header><Link className="report-brand" to="/">← Report Cybercrime</Link><span className="save-indicator"><button className="nav-button" onClick={save} disabled={saving}>{saving?'Saving…':'Save'}</button><button className="nav-button exit-button" onClick={() => navigate('/')}>Exit</button></span></header><main>{children}</main><footer><div className="help-footer">Need Help?</div><div className="brandline"><span>NCRP</span><span>Government of India</span></div><div className="footer-credit">A Project made for "Build What Moves India" Hackathon by Varun Mayya</div></footer></div> }
