import React, { useEffect, useState } from 'react'
import { useParams } from 'react-router-dom'
import { api } from '../services/api'
import { Button, ErrorBox, Loading } from '../components/common'

export default function AdminActivity({ caseId: providedCaseId }) {
  const { caseId: routeCaseId } = useParams(); const caseId = providedCaseId || routeCaseId
  const [requests, setRequests] = useState([]); const [loadingRequests, setLoadingRequests] = useState(true)
  const [event, setEvent] = useState({ type: 'STATUS_UPDATE', title: '', description: '', stage: '', actor: '', approvedBy: '', forwardedBy: '', evidenceRequestId: '' }); const [message, setMessage] = useState({ type: 'CASE_UPDATE', title: '', message: '' }); const [error, setError] = useState(); const [busy, setBusy] = useState(false); const [success, setSuccess] = useState()
  useEffect(() => { if (!caseId) { setLoadingRequests(false); return }; api.adminCase(caseId).then(data => setRequests(data.requested || data.evidence?.requested || [])).catch(setError).finally(() => setLoadingRequests(false)) }, [caseId])
  const updateEvent = (key, value) => setEvent(current => ({ ...current, [key]: value })); const updateMessage = (key, value) => setMessage(current => ({ ...current, [key]: value }))
  const addEvent = async formEvent => { formEvent.preventDefault(); if (!caseId) { setError(new Error('The case ID is missing from this admin page.')); return }; setBusy(true); setError(); setSuccess(); try { await api.adminAddTimeline(caseId, { ...event, evidenceRequestId: event.evidenceRequestId || null }); setSuccess('Timeline entry added.'); setEvent({ type: 'STATUS_UPDATE', title: '', description: '', stage: '', actor: '', approvedBy: '', forwardedBy: '', evidenceRequestId: '' }) } catch (caught) { setError(caught) } finally { setBusy(false) } }
  const addMessage = async formEvent => { formEvent.preventDefault(); if (!caseId) { setError(new Error('The case ID is missing from this admin page.')); return }; setBusy(true); setError(); setSuccess(); try { await api.adminAddMessage(caseId, message); setSuccess('Case message added.'); setMessage({ type: 'CASE_UPDATE', title: '', message: '' }) } catch (caught) { setError(caught) } finally { setBusy(false) } }
  if (loadingRequests) return <div className="detail-main admin-activity"><Loading text="Loading case activity options…"/></div>
  return <div className="detail-main admin-activity"><p className="eyebrow">ADMIN ACTIVITY CONTROLS</p><h1>Add case activity</h1><p>Development-only controls for populating the citizen timeline and messages views.</p><ErrorBox error={error}/>{success && <div className="alert">{success}</div>}<div className="admin-grid"><section className="panel"><h2>Add timeline entry</h2><form onSubmit={addEvent}><label>Event type<select value={event.type} onChange={e=>updateEvent('type',e.target.value)}><option>STATUS_UPDATE</option><option>ASSIGNED</option><option>FORWARDED</option><option>APPROVED</option><option>EVIDENCE_REQUESTED</option><option>RESOLVED</option></select></label><label>Title<input value={event.title} onChange={e=>updateEvent('title',e.target.value)} required placeholder="Case assigned"/></label><label>Description<textarea value={event.description} onChange={e=>updateEvent('description',e.target.value)} required placeholder="The complaint was assigned to the cybercrime unit."/></label><label>Stage<input value={event.stage} onChange={e=>updateEvent('stage',e.target.value)} placeholder="Investigation"/></label><label>Handled by<input value={event.actor} onChange={e=>updateEvent('actor',e.target.value)} placeholder="Cyber Crime Unit"/></label><label>Approved by<input value={event.approvedBy} onChange={e=>updateEvent('approvedBy',e.target.value)}/></label><label>Forwarded by<input value={event.forwardedBy} onChange={e=>updateEvent('forwardedBy',e.target.value)}/></label><label>Evidence request <span className="optional">optional</span>{requests.length ? <select value={event.evidenceRequestId} onChange={e=>updateEvent('evidenceRequestId',e.target.value)}><option value="">No evidence request</option>{requests.filter(item=>item.status !== 'FULFILLED').map(item=><option value={item.id} key={item.id}>{item.tag} · {item.id}</option>)}</select> : <span className="field-note">No evidence requests exist for this case.</span>}</label><Button primary disabled={busy}>{busy?'Saving…':'Add timeline entry'}</Button></form></section><section className="panel"><h2>Add case message</h2><form onSubmit={addMessage}><label>Message type<select value={message.type} onChange={e=>updateMessage('type',e.target.value)}><option>CASE_UPDATE</option><option>EVIDENCE_REQUEST</option><option>ASSIGNMENT</option><option>RESOLUTION</option></select></label><label>Title<input value={message.title} onChange={e=>updateMessage('title',e.target.value)} required placeholder="Your complaint has been assigned"/></label><label>Message<textarea value={message.message} onChange={e=>updateMessage('message',e.target.value)} required placeholder="The investigating unit is reviewing your complaint."/></label><Button primary disabled={busy}>{busy?'Sending…':'Add message'}</Button></form></section></div></div>
}
