import React, { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { api } from '../services/api'
import { Button, ErrorBox, Loading } from '../components/common'

const STATUSES = ['SUBMITTED', 'UNDER_REVIEW', 'IN_PROGRESS', 'ACTION_REQUIRED', 'RESOLVED', 'CLOSED']

export default function AdminCase() {
  const { caseId } = useParams()
  const [data, setData] = useState(); const [status, setStatus] = useState(''); const [tag, setTag] = useState('Additional documents'); const [description, setDescription] = useState(''); const [error, setError] = useState(); const [busy, setBusy] = useState(false); const [message, setMessage] = useState()
  const load = () => api.adminCase(caseId).then(value => { setData(value); setStatus(value.case?.status || value.status || '') }).catch(setError)
  useEffect(() => { load() }, [caseId])
  const updateStatus = async event => { event.preventDefault(); setBusy(true); setError(); setMessage(); try { await api.adminUpdateCaseStatus(caseId, { status }); setMessage('Case status updated.'); await load() } catch (caught) { setError(caught) } finally { setBusy(false) } }
  const requestEvidence = async event => { event.preventDefault(); setBusy(true); setError(); setMessage(); try { await api.adminRequestEvidence(caseId, { tag, description }); setDescription(''); setMessage('Evidence request added.'); await load() } catch (caught) { setError(caught) } finally { setBusy(false) } }
  if (!data) return error ? <ErrorBox error={error} /> : <Loading />
  const currentCase = data.case || data; const submitted = data.submitted || data.evidence?.submitted || []; const requested = data.requested || data.evidence?.requested || []
  return <div className="detail-main admin-page"><Link to={`/cases/${caseId}`}>← Back to Case Home</Link><p className="eyebrow">ADMIN PREVIEW · NO CREDENTIALS</p><h1>Manage case</h1><p><strong>{currentCase.caseNumber || caseId}</strong> · {currentCase.category || 'Cybercrime report'}</p><span className="status">{currentCase.status}</span><ErrorBox error={error}/>{message && <div className="alert">{message}</div>}<div className="admin-grid"><section className="panel"><h2>Change case status</h2><p>Development-only control for testing citizen case journeys.</p><form onSubmit={updateStatus}><label>New status<select value={status} onChange={event => setStatus(event.target.value)}>{STATUSES.map(item => <option key={item}>{item}</option>)}</select></label><Button primary disabled={busy || !status}>{busy ? 'Saving…' : 'Update status'}</Button></form></section><section className="panel"><h2>Request evidence</h2><p>The request will appear on the citizen’s Case Evidence page.</p><form onSubmit={requestEvidence}><label>Evidence needed<input value={tag} onChange={event => setTag(event.target.value)} required placeholder="Bank statement" /></label><label>Instructions<textarea value={description} onChange={event => setDescription(event.target.value)} required placeholder="Explain what the citizen should provide." /></label><Button primary disabled={busy || !tag.trim() || !description.trim()}>{busy ? 'Sending…' : 'Request evidence'}</Button></form></section></div><div className="admin-evidence-grid"><section className="panel"><h2>Submitted evidence</h2>{submitted.length ? submitted.map(item => <div className="admin-evidence-item" key={item.id}><strong>{item.filename || item.tag || 'Evidence'}</strong><small>{item.tag}{item.description ? ` · ${item.description}` : ''}</small></div>) : <p className="hint">No submitted evidence.</p>}</section><section className="panel"><h2>Evidence requests</h2>{requested.length ? requested.map(item => <div className="admin-evidence-item" key={item.id}><strong>{item.tag}</strong><small>{item.status || 'OPEN'}{item.description ? ` · ${item.description}` : ''}</small></div>) : <p className="hint">No evidence requests yet.</p>}</section></div></div>
}
