import React, { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { api } from '../services/api'
import { downloadFile } from '../services/api/client'
import { Button, ErrorBox, Loading } from '../components/common'

const labelize = key => key.replaceAll('_', ' ').replace(/\b\w/g, letter => letter.toUpperCase())
const display = value => { if (value === null || value === undefined || value === '') return 'Not provided'; if (typeof value === 'boolean') return value ? 'Yes' : 'No'; if (Array.isArray(value)) return value.join(', '); if (typeof value === 'object') return Object.entries(value).map(([key, item]) => `${labelize(key)}: ${display(item)}`).join(' · '); return String(value) }

function ReportSection({ section }) { const items = section.items || section.fields || []; return <section className="structured-section"><h3>{section.title || section.name || 'Report section'}</h3>{items.length ? <div className="structured-items">{items.map((item, index) => <div className="structured-item" key={item.id || item.label || index}><small>{item.label || item.name || 'Information'}</small><strong>{display(item.value ?? item.content)}</strong></div>)}</div> : <p>{display(section.value)}</p>}</section> }

export default function CaseDetails() {
  const { caseId } = useParams(); const [data, setData] = useState(); const [error, setError] = useState(); const [downloading, setDownloading] = useState(false)
  useEffect(() => { api.caseDetails(caseId).then(setData).catch(setError) }, [caseId])
  const download = async () => { setDownloading(true); setError(); try { await downloadFile(`/api/v1/cases/${caseId}/report.pdf`, `NCRP-${data.case?.caseNumber || caseId}.pdf`) } catch (caught) { setError(caught) } finally { setDownloading(false) } }
if (!data) return error ? <ErrorBox error={error} onRetry={() => window.location.reload()}/> : <Loading text="Loading report details…"/>
  const currentCase = data.case || {}; const answers = data.answers || data.information || {}; const report = data.structuredReport || data.report || {}; const sections = report.sections || []
  return <div className="detail-main case-details-page"><Link to={`/cases/${caseId}`}>← Back to Case Home</Link><div className="details-heading"><div><p className="eyebrow">CASE DETAILS</p><h1>{currentCase.category || 'Cybercrime report'}</h1><p className="case-id"><strong>Case ID</strong> {currentCase.id || caseId}<br/><strong>Case number</strong> {currentCase.caseNumber || 'Not assigned'}</p></div><div className="details-heading-actions"><span className="status">{currentCase.status || 'UNKNOWN'}</span><Button primary onClick={download} disabled={downloading}>{downloading ? 'Preparing PDF…' : 'Download report PDF'}</Button></div></div><section className="panel case-summary"><h2>Case summary</h2><div className="summary-grid"><div><small>Status</small><strong>{currentCase.status || 'Not available'}</strong></div><div><small>Submitted</small><strong>{currentCase.submittedAt ? new Date(currentCase.submittedAt).toLocaleString() : 'Not available'}</strong></div><div><small>Category</small><strong>{currentCase.category || 'Not available'}</strong></div><div><small>Reference</small><strong>{currentCase.caseNumber || currentCase.id || caseId}</strong></div></div></section><section className="panel"><h2>Information provided</h2>{Object.keys(answers).length ? <div className="details-answer-grid">{Object.entries(answers).map(([key, value]) => <div className="detail-answer" key={key}><small>{labelize(key)}</small><strong>{display(value)}</strong></div>)}</div> : <p className="hint">No questionnaire information was returned.</p>}</section><section className="panel structured-report"><div className="structured-header"><div><p className="eyebrow">GENERATED REPORT</p><h2>{report.title || 'Structured report'}</h2></div><span className="report-badge">Official case record</span></div>{sections.length ? sections.map((section, index) => <ReportSection section={section} key={section.id || section.title || index}/>) : Object.keys(report).length ? <div className="details-answer-grid">{Object.entries(report).filter(([key]) => key !== 'title').map(([key, value]) => <div className="detail-answer" key={key}><small>{labelize(key)}</small><strong>{display(value)}</strong></div>)}</div> : <p className="hint">The structured report is not available yet.</p>}</section><ErrorBox error={error}/></div>
}
