import React from 'react'
import { Link, useParams } from 'react-router-dom'
import { api } from '../services/api'
import { ErrorBox, Loading } from '../components/common'
import { useAsync } from '../hooks/useAsync'
const formatDate = value => value ? new Date(value).toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' }) : 'Date unavailable'
const title = value => String(value || '').replaceAll('_', ' ').replace(/\b\w/g, letter => letter.toUpperCase())
export function CaseTimeline() { const { caseId } = useParams(); const state = useAsync(() => api.timeline(caseId), [caseId]); if (state.loading) return <Loading text="Loading your report timeline…"/>; if (state.error) return <ErrorBox error={state.error}/>; const events = state.data.events || []; return <div className="activity-page detail-main"><Link className="back-link" to={`/cases/${caseId}`}>← Back to report overview</Link><p className="eyebrow">REPORT PROGRESS</p><h1>Progress timeline</h1><p className="page-description">See the stages your report has passed through and any action needed from you.</p>{events.length ? <div className="timeline-journey">{events.map((event, index) => <article className="timeline-event" key={event.id || index}><div className="timeline-marker"><span>{index + 1}</span></div><div className="timeline-event-body"><div className="timeline-meta"><span>{formatDate(event.createdAt)}</span>{event.stage && <span className="event-stage">{title(event.stage)}</span>}</div><h2>{event.title || title(event.type)}</h2>{event.description && <p>{event.description}</p>}<div className="event-details">{event.actor && <span><small>Handled by</small><strong>{event.actor}</strong></span>}{event.approvedBy && <span><small>Approved by</small><strong>{event.approvedBy}</strong></span>}{event.forwardedBy && <span><small>Forwarded by</small><strong>{event.forwardedBy}</strong></span>}</div>{event.evidenceRequestId && <Link className="button small-button" to={`/cases/${caseId}/evidence`}>View requested evidence <span aria-hidden="true">→</span></Link>}</div></article>)}</div> : <div className="empty"><strong>No updates yet</strong><p>Your report updates will appear here as it moves through the process.</p></div>}</div> }
export function CaseMessages() { const { caseId } = useParams(); const state = useAsync(() => api.messages(caseId), [caseId]); if (state.loading) return <Loading text="Loading messages…"/>; if (state.error) return <ErrorBox error={state.error}/>; const messages = state.data.messages || []; return <div className="activity-page detail-main"><Link className="back-link" to={`/cases/${caseId}`}>← Back to report overview</Link><p className="eyebrow">REPORT COMMUNICATION</p><h1>Messages</h1><p className="page-description">Important updates about your report appear here.</p>{messages.length ? <div className="message-feed">{messages.map((item, index) => <article className="message-card" key={item.id || index}><div className="message-card-top"><span className="message-type">{title(item.type || 'CASE_UPDATE')}</span><time>{formatDate(item.createdAt)}</time></div><h2>{item.title || 'Report update'}</h2><p>{item.message || item.description}</p>{item.sender && <small>From {item.sender}</small>}</article>)}</div> : <div className="empty"><strong>No messages yet</strong><p>Updates from the investigating team will appear here.</p></div>}</div> }
